# =========================
# EMAIL - Example
# =========================
spring.mail.username=GMAIL_CUA_NHOM
spring.mail.password=APP_PASSWORD_CUA_NHOM

# =========================
# Cloudflare R2 - Example
# =========================

cloudflare.r2.account-id= ...

cloudflare.r2.access-key=....

cloudflare.r2.secret-key=...

cloudflare.r2.bucket=quanlybenhvien-images
